server:
  port: 9012
  
  
spring:
  application:
    name: security-demo
    
    

  
    
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

      

  datasource:
    url: jdbc:h2:mem:devdb
#    username: Rahul
#    password: "!@123Rahul"
    
   security:    user:      name: Rahul
      password: 12345
      roles:      - Admin  h2:    console:      enabled: true  jpa:    show-sql: true    hibernate:      ddl-auto: update
      
